// ============================================================
// auto-generated by vue-to-ts from tiny.vue
// source kind: <script setup>, lang: ts
// edits will be overwritten on next run
// ============================================================

import { defineComponent as _defineComponent } from 'vue'
import { ref } from 'vue';


export default /*@__PURE__*/_defineComponent({
  __name: 'tiny',
  setup(__props, { expose: __expose }) {
  __expose();

const msg = ref('hi');

function greet() {
  return msg.value;
}

const __returned__ = { msg, greet }
Object.defineProperty(__returned__, '__isScriptSetup', { enumerable: false, value: true })
return __returned__
}

})
//# sourceMappingURL=tiny.vue.ts.map
